/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jard;

/**
 *
 * @author vicOMG99
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuP = new javax.swing.JPanel();
        btnRegiostroProfesores = new javax.swing.JButton();
        btnAlumno = new javax.swing.JButton();
        btnRegistroPadre = new javax.swing.JButton();
        btnAsistencia = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenuP.setBackground(new java.awt.Color(224, 247, 250));
        panelMenuP.setLayout(null);

        btnRegiostroProfesores.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnRegiostroProfesores.setText("Registro Profesores");
        btnRegiostroProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegiostroProfesoresMouseClicked(evt);
            }
        });
        panelMenuP.add(btnRegiostroProfesores);
        btnRegiostroProfesores.setBounds(80, 70, 195, 29);

        btnAlumno.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnAlumno.setText("Registro Alumno");
        btnAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlumnoMouseClicked(evt);
            }
        });
        panelMenuP.add(btnAlumno);
        btnAlumno.setBounds(80, 150, 190, 29);

        btnRegistroPadre.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnRegistroPadre.setText("Registro Padre");
        panelMenuP.add(btnRegistroPadre);
        btnRegistroPadre.setBounds(80, 230, 190, 29);

        btnAsistencia.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnAsistencia.setText("Registro Asistencia");
        btnAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsistenciaMouseClicked(evt);
            }
        });
        panelMenuP.add(btnAsistencia);
        btnAsistencia.setBounds(80, 320, 189, 29);

        jPanel1.setBackground(new java.awt.Color(9, 9, 68));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelMenuP.add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuP, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegiostroProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegiostroProfesoresMouseClicked
        RegistroProfesores obj = new RegistroProfesores();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegiostroProfesoresMouseClicked

    private void btnAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlumnoMouseClicked
        RegistroNiños obj = new RegistroNiños();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAlumnoMouseClicked

    private void btnAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsistenciaMouseClicked
        registroEntrada obj = new registroEntrada();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAsistenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumno;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnRegiostroProfesores;
    private javax.swing.JButton btnRegistroPadre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelMenuP;
    // End of variables declaration//GEN-END:variables
}
